### ISSUE TITLE
Ideas to differentiate between days in the timeline

### ISSUE THREAD

**Issue by kaelig** [kvendrik/timeline-client-web#2]
At the moment browsing a timeline looks very linear and days aren't clearly separated.

Here are a few ideas to remedy this:

- Different icon for start of day & end of day
- Visual hint (horizontal rule, gradient…)
- Date in a different font format (bold, caps…?)

**Comment by kvendrik** [comment]
fixed in https://github.com/kvendrik/timeline-client-web/pull/6
